spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: sa-east-1
      auto: false
    credentials:
      access-key: xxx
      secret-key: xxx
    topic:
      name: arn:aws:sns:sa-east-1:xxx:topic-sms